#!/bin/sh

module_wifi_kit_plan() {
  case "${SEED_KIT_LANG:-en}" in
    fr)
      echo "Seed-Kit > plan - wifi-kit"
      echo ""
      echo "Mode : SAFE lecture seule"
      echo ""
      echo "Contrat module :"
      echo "- id : wifi-kit"
      echo "- type : network-ui"
      echo "- plateforme : raspberrypi/debian"
      echo "- backend : networkmanager"
      echo "- mode : normal-ui + ap-recovery"
      echo ""
      echo "Dépendances requises :"
      echo "- python3"
      echo "- network-manager"
      echo "- nmcli"
      echo "- wpasupplicant / wpa_cli"
      echo "- iw"
      echo "- iproute2"
      echo ""
      echo "Dépendances recommandées :"
      echo "- rfkill recommandé"
      echo ""
      echo "Dépendances conditionnelles :"
      echo "- scan Wi-Fi : network-manager, nmcli, wpa_cli, iw"
      echo "- UI normale : python3, fichiers UI, port 54321 libre"
      echo "- recovery AP : hostapd, dnsmasq, wrapper privilégié, sudoers strict"
      echo "- boot cleanup guard : wrapper/guard Wifi-Kit, NetworkManager"
      echo ""
      echo "Capabilities :"
      echo "- normal-ui"
      echo "- wifi-scan"
      echo "- return-default-network"
      echo "- ap-recovery"
      echo "- recovery-guard"
      echo "- readiness-preview"
      echo "- uninstall-preview"
      echo ""
      echo "Persistant futur :"
      echo "- paquets système installés"
      echo "- fichiers module sous /opt/seed-kit/wifi-kit/"
      echo "- configuration sous /etc/seed-kit/wifi-kit/"
      echo "- logs sous /var/log/seed-kit/wifi-kit/"
      echo "- état runtime sous /run/seed-kit/wifi-kit/"
      echo ""
      echo "Temporaire :"
      echo "- vérifications"
      echo "- staging éventuel"
      echo "- hostapd/dnsmasq seulement pendant recovery explicite"
      echo ""
      echo "Ne fera pas :"
      echo "- démarrer un AP"
      echo "- modifier le réseau courant"
      echo "- appliquer sudoers"
      echo "- installer service systemd"
      echo "- lancer l'UI normale"
      echo "- écrire de secret"
      echo "- supprimer des profils Wi-Fi"
      echo "- reboot/restart réseau"
      echo ""
      echo "Runtime futur :"
      echo "- UI normale : port 54321"
      echo "- recovery captive : port 80 seulement en mode AP explicite"
      echo "- SSID recovery : Wifi-Kit-<hostname>"
      echo "- IP AP recovery : 192.168.50.1/24"
      echo "- DHCP recovery : 192.168.50.20-192.168.50.80"
      echo ""
      echo "Sous-plans futurs :"
      echo "- install-packages"
      echo "- install-files"
      echo "- configure-sudoers-preview"
      echo "- install-service-preview"
      echo "- recovery-preview"
      echo "- readiness-preview"
      echo "- uninstall-preview"
      ;;
    *)
      echo "Seed-Kit > plan - wifi-kit"
      echo ""
      echo "Mode: SAFE read-only"
      echo ""
      echo "Module contract:"
      echo "- id: wifi-kit"
      echo "- type: network-ui"
      echo "- platform: raspberrypi/debian"
      echo "- backend: networkmanager"
      echo "- mode: normal-ui + ap-recovery"
      echo ""
      echo "Required dependencies:"
      echo "- python3"
      echo "- network-manager"
      echo "- nmcli"
      echo "- wpasupplicant / wpa_cli"
      echo "- iw"
      echo "- iproute2"
      echo ""
      echo "Recommended dependencies:"
      echo "- rfkill recommended"
      echo ""
      echo "Conditional dependencies:"
      echo "- Wi-Fi scan: network-manager, nmcli, wpa_cli, iw"
      echo "- normal UI: python3, UI files, free port 54321"
      echo "- recovery AP: hostapd, dnsmasq, privileged wrapper, strict sudoers"
      echo "- boot cleanup guard: Wifi-Kit wrapper/guard, NetworkManager"
      echo ""
      echo "Capabilities:"
      echo "- normal-ui"
      echo "- wifi-scan"
      echo "- return-default-network"
      echo "- ap-recovery"
      echo "- recovery-guard"
      echo "- readiness-preview"
      echo "- uninstall-preview"
      echo ""
      echo "Future persistent state:"
      echo "- system packages installed"
      echo "- module files under /opt/seed-kit/wifi-kit/"
      echo "- configuration under /etc/seed-kit/wifi-kit/"
      echo "- logs under /var/log/seed-kit/wifi-kit/"
      echo "- runtime state under /run/seed-kit/wifi-kit/"
      echo ""
      echo "Temporary:"
      echo "- checks"
      echo "- optional staging"
      echo "- hostapd/dnsmasq only during explicit recovery"
      echo ""
      echo "Will not:"
      echo "- start an AP"
      echo "- change the current network"
      echo "- apply sudoers"
      echo "- install a systemd service"
      echo "- launch the normal UI"
      echo "- write secrets"
      echo "- delete Wi-Fi profiles"
      echo "- reboot/restart networking"
      echo ""
      echo "Future runtime:"
      echo "- normal UI: port 54321"
      echo "- recovery captive portal: port 80 only in explicit AP mode"
      echo "- recovery SSID: Wifi-Kit-<hostname>"
      echo "- recovery AP IP: 192.168.50.1/24"
      echo "- recovery DHCP: 192.168.50.20-192.168.50.80"
      echo ""
      echo "Future sub-plans:"
      echo "- install-packages"
      echo "- install-files"
      echo "- configure-sudoers-preview"
      echo "- install-service-preview"
      echo "- recovery-preview"
      echo "- readiness-preview"
      echo "- uninstall-preview"
      ;;
  esac
}

module_wifi_kit_dependencies() {
  echo "Wifi-Kit dependencies"
  echo ""
  echo "Module:"
  echo "- id: wifi-kit"
  echo "- type: network-ui"
  echo "- platform: raspberrypi/debian"
  echo "- backend: networkmanager"
  echo "- mode: normal-ui + ap-recovery"
  echo ""
  echo "Required system packages:"
  echo "- python3"
  echo "- network-manager"
  echo "- nmcli"
  echo "- wpasupplicant / wpa_cli"
  echo "- iw"
  echo "- iproute2"
  echo ""
  echo "Recommended system packages:"
  echo "- rfkill (recommended)"
  echo ""
  echo "Conditional dependencies:"
  echo "- wifi-scan: network-manager, nmcli, wpa_cli, iw"
  echo "- normal-ui: python3, UI files, free port 54321"
  echo "- ap-recovery: hostapd, dnsmasq, privileged wrapper, strict sudoers"
  echo "- return-default-network: NetworkManager, wrapper action"
  echo "- boot-cleanup-guard: recovery guard, module-scoped runtime state"
  echo ""
  echo "Capabilities:"
  echo "- normal-ui"
  echo "- wifi-scan"
  echo "- return-default-network"
  echo "- ap-recovery"
  echo "- recovery-guard"
  echo "- readiness-checks"
  echo "- health-checks"
  echo "- uninstall-preview"
  echo ""
  echo "Install files:"
  echo "- prototype/ui/serve-readonly.py"
  echo "- prototype/ui/index.html"
  echo "- prototype/ap-setup-test.sh"
  echo "- prototype/wifi-kit-connect-recovery.sh"
  echo "- prototype/wifi-kit-recovery-guard.sh"
  echo "- prototype/wifi-kit-action-wrapper.sh"
  echo ""
  echo "Target paths:"
  echo "- /opt/seed-kit/wifi-kit/"
  echo "- /etc/seed-kit/wifi-kit/"
  echo "- /var/log/seed-kit/wifi-kit/"
  echo "- /run/seed-kit/wifi-kit/"
  echo ""
  echo "Future runtime:"
  echo "- normal UI port: 54321"
  echo "- normal UI command: python3 /opt/seed-kit/wifi-kit/ui/serve-readonly.py --host 0.0.0.0 --port 54321"
  echo "- recovery captive portal: 80"
  echo "- AP mode: explicit only"
  echo "- recovery SSID: Wifi-Kit-<hostname>"
  echo "- recovery AP IP: 192.168.50.1/24"
  echo "- recovery DHCP: 192.168.50.20-192.168.50.80"
  echo ""
  echo "Privileged wrapper:"
  echo "- path: /opt/seed-kit/wifi-kit/wifi-kit-action-wrapper.sh"
  echo "- allowed action: start-ap-mode"
  echo "- allowed action: return-default-network"
  echo "- no arbitrary shell"
  echo "- no free-form user arguments"
  echo ""
  echo "Sudoers requirements:"
  echo "- NOPASSWD only for the wrapper path"
  echo "- no sudo shell"
  echo "- no broad nmcli"
  echo "- no broad systemctl"
  echo "- not applied during plan phase"
  echo ""
  echo "Persistent config:"
  echo "- recovery_ssid"
  echo "- recovery_ap_password"
  echo "- normal_ui_port: 54321"
  echo "- recovery_ui_port: 80"
  echo "- default_network_connection"
  echo "- timeouts"
  echo "- stored outside Git with strict permissions"
  echo ""
  echo "Readiness checks:"
  echo "- dependencies present"
  echo "- wlan0 present"
  echo "- NetworkManager running"
  echo "- nmcli usable"
  echo "- wpa_cli usable"
  echo "- port 54321 free"
  echo "- no active Wifi-Kit recovery leftovers"
  echo ""
  echo "Health checks:"
  echo "- /status responds"
  echo "- scan works"
  echo "- wlan0 state readable"
  echo "- no unexpected hostapd/dnsmasq in normal mode"
  echo "- recovery guard clean"
  echo ""
  echo "Future previews:"
  echo "- validate"
  echo "- install-packages"
  echo "- install-files"
  echo "- configure-sudoers-preview"
  echo "- install-service-preview"
  echo "- recovery-preview"
  echo "- readiness-preview"
  echo "- uninstall-preview"
  echo ""
  echo "Rollback/uninstall preview:"
  echo "- stop UI"
  echo "- stop recovery if active"
  echo "- run recovery guard cleanup"
  echo "- remove sudoers rule"
  echo "- remove service"
  echo "- remove installed files"
  echo "- preserve user Wi-Fi profiles unless explicitly confirmed"
  echo ""
  echo "Safety:"
  echo "- no AP at boot"
  echo "- no sudoers applied"
  echo "- no network changes"
  echo "- no services installed"
  echo "- no secrets"
  echo "- no reboot"
  echo "- no Wi-Fi profiles deleted"
  echo "- no AP+STA permanent assumption"
  echo "- no arbitrary shell commands"
}

module_wifi_kit_contract() {
  case "${1:-print}" in
    print|validate)
      module_wifi_kit_contract_print
      ;;
    dependencies)
      module_wifi_kit_dependencies
      ;;
    *)
      echo "unknown wifi-kit contract mode: $1" >&2
      return 2
      ;;
  esac
}

module_wifi_kit_contract_print() {
  echo "WIFI_KIT_MODULE_ID=wifi-kit"
  echo "WIFI_KIT_MODULE_TYPE=network-ui"
  echo "WIFI_KIT_BACKEND=networkmanager"
  echo "WIFI_KIT_MODE=normal-ui+ap-recovery"
  echo "WIFI_KIT_RUNTIME_UI_NORMAL_PORT=54321"
  echo "WIFI_KIT_RUNTIME_UI_RECOVERY_PORT=80"
  echo "WIFI_KIT_DEPENDENCIES_REQUIRED=python3"
  echo "WIFI_KIT_DEPENDENCIES_REQUIRED=network-manager"
  echo "WIFI_KIT_DEPENDENCIES_REQUIRED=nmcli"
  echo "WIFI_KIT_DEPENDENCIES_REQUIRED=wpa_cli"
  echo "WIFI_KIT_DEPENDENCIES_REQUIRED=iw"
  echo "WIFI_KIT_DEPENDENCIES_REQUIRED=iproute2"
  echo "WIFI_KIT_DEPENDENCIES_RECOMMENDED=rfkill"
  echo "WIFI_KIT_DEPENDENCIES_CONDITIONAL=hostapd"
  echo "WIFI_KIT_DEPENDENCIES_CONDITIONAL=dnsmasq"
  echo "WIFI_KIT_DEPENDENCIES_CONDITIONAL=sudoers-wrapper"
  echo "WIFI_KIT_DEPENDENCIES_CONDITIONAL=systemd-service"
  echo "WIFI_KIT_CAPABILITIES=normal-ui"
  echo "WIFI_KIT_CAPABILITIES=wifi-scan"
  echo "WIFI_KIT_CAPABILITIES=wifi-connect-recovery"
  echo "WIFI_KIT_CAPABILITIES=ap-recovery"
  echo "WIFI_KIT_CAPABILITIES=captive-portal"
  echo "WIFI_KIT_CAPABILITIES=recovery-cleanup"
  echo "WIFI_KIT_CAPABILITIES=privileged-actions"
  echo "WIFI_KIT_FILES=prototype/ui/serve-readonly.py"
  echo "WIFI_KIT_FILES=prototype/ui/index.html"
  echo "WIFI_KIT_FILES=prototype/ap-setup-test.sh"
  echo "WIFI_KIT_FILES=prototype/wifi-kit-connect-recovery.sh"
  echo "WIFI_KIT_FILES=prototype/wifi-kit-recovery-guard.sh"
  echo "WIFI_KIT_FILES=prototype/wifi-kit-action-wrapper.sh"
  echo "WIFI_KIT_TARGET_PATH_APP_DIR=/opt/seed-kit/wifi-kit"
  echo "WIFI_KIT_TARGET_PATH_CONFIG_DIR=/etc/seed-kit/wifi-kit"
  echo "WIFI_KIT_TARGET_PATH_LOG_DIR=/var/log/seed-kit/wifi-kit"
  echo "WIFI_KIT_TARGET_PATH_RUNTIME_DIR=/run/seed-kit/wifi-kit"
  echo "WIFI_KIT_RUNTIME_SERVICE_NAME=seed-kit-wifi-kit-ui.service"
  echo "WIFI_KIT_RUNTIME_SERVICE_COMMAND=python3 /opt/seed-kit/wifi-kit/ui/serve-readonly.py --host 0.0.0.0 --port 54321"
  echo "WIFI_KIT_RUNTIME_SERVICE_USER=non-root preferred"
  echo "WIFI_KIT_RUNTIME_SERVICE_AUTOSTART=yes"
  echo "WIFI_KIT_PRIVILEGED_WRAPPER_PATH=/opt/seed-kit/wifi-kit/wifi-kit-action-wrapper.sh"
  echo "WIFI_KIT_PRIVILEGED_ACTIONS=start-ap-mode"
  echo "WIFI_KIT_PRIVILEGED_ACTIONS=return-default-network"
  echo "WIFI_KIT_SUDOERS_REQUIREMENTS=NOPASSWD only for wrapper path"
  echo "WIFI_KIT_SUDOERS_REQUIREMENTS=no sudo shell"
  echo "WIFI_KIT_SUDOERS_REQUIREMENTS=no broad nmcli/systemctl"
  echo "WIFI_KIT_RECOVERY_AP_SSID=Wifi-Kit-<hostname>"
  echo "WIFI_KIT_RECOVERY_AP_IP=192.168.50.1/24"
  echo "WIFI_KIT_RECOVERY_DHCP_RANGE=192.168.50.20-192.168.50.80"
  echo "WIFI_KIT_FORBIDDEN_ACTIONS=no-reboot"
  echo "WIFI_KIT_FORBIDDEN_ACTIONS=no-ap-start-without-explicit-action"
  echo "WIFI_KIT_FORBIDDEN_ACTIONS=no-sudoers-write-in-dry-run"
  echo "WIFI_KIT_FORBIDDEN_ACTIONS=no-secret-in-git"
  echo "WIFI_KIT_FORBIDDEN_ACTIONS=no-arbitrary-shell-command"
}

module_wifi_kit_apply() {
  echo "- SAFE apply simulation (dry-run only)"
  echo "- no real network action: no hostapd, no dnsmasq, no NetworkManager"
  echo "- no Wi-Fi secrets are read, written, or logged"
  echo "- check docs: modules/wifi-kit/README.md"
  echo "- check prototype: modules/wifi-kit/prototype/wifi-kit.sh"

  if ! command -v sh >/dev/null 2>&1; then
    echo "- simulation blocked: sh unavailable"
    return 1
  fi

  if [ -f modules/wifi-kit/prototype/wifi-kit.sh ]; then
    echo "- status simulation"
    sh modules/wifi-kit/prototype/wifi-kit.sh status
    echo "- scan simulation"
    sh modules/wifi-kit/prototype/wifi-kit.sh scan
    echo "- reconnect-plan simulation"
    sh modules/wifi-kit/prototype/wifi-kit.sh reconnect-plan
    echo "- recovery-plan simulation"
    sh modules/wifi-kit/prototype/wifi-kit.sh recovery-plan
    return 0
  fi

  echo "- prototype script is missing (non-blocking for core integration testing)"
  return 1
}
