#!/bin/sh

module_wifi_kit_plan() {
  case "${SEED_KIT_LANG:-en}" in
    fr)
      echo "Seed-Kit > plan - wifi-kit"
      echo ""
      echo "Mode : SAFE lecture seule"
      echo ""
      echo "Dépendances système :"
      echo "- python3"
      echo "- network-manager"
      echo "- nmcli"
      echo "- wpasupplicant / wpa_cli"
      echo "- hostapd"
      echo "- dnsmasq"
      echo "- iw"
      echo "- iproute2"
      echo "- rfkill recommandé"
      echo ""
      echo "Persistant futur :"
      echo "- paquets système installés"
      echo "- fichiers module sous /opt/seed-kit/wifi-kit/"
      echo "- configuration sous /etc/seed-kit/wifi-kit/"
      echo "- logs sous /var/log/seed-kit/wifi-kit/"
      echo "- état runtime sous /run/seed-kit/wifi-kit/"
      echo ""
      echo "Temporaire :"
      echo "- vérifications"
      echo "- staging éventuel"
      echo "- hostapd/dnsmasq seulement pendant recovery explicite"
      echo ""
      echo "Ne fera pas :"
      echo "- démarrer un AP"
      echo "- modifier le réseau courant"
      echo "- appliquer sudoers"
      echo "- installer service systemd"
      echo "- lancer l'UI normale"
      echo "- écrire de secret"
      echo "- supprimer des profils Wi-Fi"
      echo "- reboot/restart réseau"
      echo ""
      echo "Runtime futur :"
      echo "- UI normale : port 54321"
      echo "- recovery captive : port 80 seulement en mode AP explicite"
      echo "- SSID recovery : Wifi-Kit-<hostname>"
      echo "- IP AP recovery : 192.168.50.1/24"
      echo "- DHCP recovery : 192.168.50.20-192.168.50.80"
      echo ""
      echo "Sous-plans futurs :"
      echo "- install-packages"
      echo "- install-files"
      echo "- configure-sudoers-preview"
      echo "- install-service-preview"
      echo "- recovery-preview"
      echo "- readiness-preview"
      echo "- uninstall-preview"
      ;;
    *)
      echo "Seed-Kit > plan - wifi-kit"
      echo ""
      echo "Mode: SAFE read-only"
      echo ""
      echo "System dependencies:"
      echo "- python3"
      echo "- network-manager"
      echo "- nmcli"
      echo "- wpasupplicant / wpa_cli"
      echo "- hostapd"
      echo "- dnsmasq"
      echo "- iw"
      echo "- iproute2"
      echo "- rfkill recommended"
      echo ""
      echo "Future persistent state:"
      echo "- system packages installed"
      echo "- module files under /opt/seed-kit/wifi-kit/"
      echo "- configuration under /etc/seed-kit/wifi-kit/"
      echo "- logs under /var/log/seed-kit/wifi-kit/"
      echo "- runtime state under /run/seed-kit/wifi-kit/"
      echo ""
      echo "Temporary:"
      echo "- checks"
      echo "- optional staging"
      echo "- hostapd/dnsmasq only during explicit recovery"
      echo ""
      echo "Will not:"
      echo "- start an AP"
      echo "- change the current network"
      echo "- apply sudoers"
      echo "- install a systemd service"
      echo "- launch the normal UI"
      echo "- write secrets"
      echo "- delete Wi-Fi profiles"
      echo "- reboot/restart networking"
      echo ""
      echo "Future runtime:"
      echo "- normal UI: port 54321"
      echo "- recovery captive portal: port 80 only in explicit AP mode"
      echo "- recovery SSID: Wifi-Kit-<hostname>"
      echo "- recovery AP IP: 192.168.50.1/24"
      echo "- recovery DHCP: 192.168.50.20-192.168.50.80"
      echo ""
      echo "Future sub-plans:"
      echo "- install-packages"
      echo "- install-files"
      echo "- configure-sudoers-preview"
      echo "- install-service-preview"
      echo "- recovery-preview"
      echo "- readiness-preview"
      echo "- uninstall-preview"
      ;;
  esac
}

module_wifi_kit_dependencies() {
  echo "Wifi-Kit dependencies"
  echo ""
  echo "System packages:"
  echo "- python3"
  echo "- network-manager"
  echo "- nmcli"
  echo "- wpasupplicant / wpa_cli"
  echo "- hostapd"
  echo "- dnsmasq"
  echo "- iw"
  echo "- iproute2"
  echo "- rfkill (recommended)"
  echo ""
  echo "Install files:"
  echo "- prototype/ui/serve-readonly.py"
  echo "- prototype/ui/index.html"
  echo "- prototype/ap-setup-test.sh"
  echo "- prototype/wifi-kit-connect-recovery.sh"
  echo "- prototype/wifi-kit-recovery-guard.sh"
  echo "- prototype/wifi-kit-action-wrapper.sh"
  echo ""
  echo "Target paths:"
  echo "- /opt/seed-kit/wifi-kit/"
  echo "- /etc/seed-kit/wifi-kit/"
  echo "- /var/log/seed-kit/wifi-kit/"
  echo "- /run/seed-kit/wifi-kit/"
  echo ""
  echo "Future runtime:"
  echo "- normal UI port: 54321"
  echo "- normal UI command: python3 /opt/seed-kit/wifi-kit/ui/serve-readonly.py --host 0.0.0.0 --port 54321"
  echo "- recovery captive portal: 80"
  echo "- AP mode: explicit only"
  echo "- recovery SSID: Wifi-Kit-<hostname>"
  echo "- recovery AP IP: 192.168.50.1/24"
  echo "- recovery DHCP: 192.168.50.20-192.168.50.80"
  echo ""
  echo "Privileged wrapper:"
  echo "- path: /opt/seed-kit/wifi-kit/wifi-kit-action-wrapper.sh"
  echo "- allowed action: start-ap-mode"
  echo "- allowed action: return-default-network"
  echo "- no arbitrary shell"
  echo "- no free-form user arguments"
  echo ""
  echo "Future previews:"
  echo "- install-packages"
  echo "- install-files"
  echo "- configure-sudoers-preview"
  echo "- install-service-preview"
  echo "- recovery-preview"
  echo "- readiness-preview"
  echo "- uninstall-preview"
  echo ""
  echo "Safety:"
  echo "- no AP at boot"
  echo "- no sudoers applied"
  echo "- no network changes"
  echo "- no services installed"
  echo "- no secrets"
  echo "- no reboot"
  echo "- no Wi-Fi profiles deleted"
}

module_wifi_kit_apply() {
  echo "- SAFE apply simulation (dry-run only)"
  echo "- no real network action: no hostapd, no dnsmasq, no NetworkManager"
  echo "- no Wi-Fi secrets are read, written, or logged"
  echo "- check docs: modules/wifi-kit/README.md"
  echo "- check prototype: modules/wifi-kit/prototype/wifi-kit.sh"

  if ! command -v sh >/dev/null 2>&1; then
    echo "- simulation blocked: sh unavailable"
    return 1
  fi

  if [ -f modules/wifi-kit/prototype/wifi-kit.sh ]; then
    echo "- status simulation"
    sh modules/wifi-kit/prototype/wifi-kit.sh status
    echo "- scan simulation"
    sh modules/wifi-kit/prototype/wifi-kit.sh scan
    echo "- reconnect-plan simulation"
    sh modules/wifi-kit/prototype/wifi-kit.sh reconnect-plan
    echo "- recovery-plan simulation"
    sh modules/wifi-kit/prototype/wifi-kit.sh recovery-plan
    return 0
  fi

  echo "- prototype script is missing (non-blocking for core integration testing)"
  return 1
}
