#!/bin/sh

set -u

repo_dir="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
failures=0
total=0

run_test() {
  name="$1"
  command="$2"

  total=$((total + 1))
  echo "== $name =="
  if sh -c "$command"; then
    echo "OK: $name"
  else
    echo "FAIL: $name" >&2
    failures=$((failures + 1))
  fi
  echo
}

run_fail_test() {
  name="$1"
  command="$2"

  total=$((total + 1))
  echo "== $name =="
  if sh -c "$command"; then
    echo "FAIL: $name" >&2
    failures=$((failures + 1))
  else
    echo "OK: $name"
  fi
  echo
}

echo "Seed-Kit smoke tests"
echo

run_test "seed-kit syntax" "cd '$repo_dir' && sh -n seed-kit.sh"
run_test "install-seed-kit syntax" "cd '$repo_dir' && sh -n install-seed-kit.sh"
run_test "seed-kit fresh-node help" "cd '$repo_dir' && sh seed-kit.sh --help | grep -q 'Fresh-node bootstrap'"
run_test "seed-kit self-update help" "cd '$repo_dir' && sh seed-kit.sh --help | grep -q 'self-update --plan'"
run_test "seed-kit self-update usage" "cd '$repo_dir' && out=\$(sh seed-kit.sh self-update 2>&1) && exit 1 || printf '%s\n' \"\$out\" | grep -q 'usage: sh seed-kit.sh self-update --plan'"
run_test "seed-kit modules list" "cd '$repo_dir' && sh seed-kit.sh modules list | grep -q 'Available modules'"
run_test "seed-kit docker dependencies" "cd '$repo_dir' && out=\$(sh seed-kit.sh modules deps docker) && printf '%s\n' \"\$out\" | grep -q 'package: docker-ce'"
run_test "seed-kit docker plan" "cd '$repo_dir' && out=\$(sh seed-kit.sh --plan --modules=docker) && printf '%s\n' \"\$out\" | grep -q 'install Docker Engine from the official Docker apt repository'"
run_test "seed-kit package plan preview" "cd '$repo_dir' && pkg=\$(mktemp -t seed-kit-package-plan.XXXXXX) && out=\$(sh seed-kit.sh --plan --package \"\$pkg\") && rm -f \"\$pkg\" && printf '%s\n' \"\$out\" | grep -q 'Package-driven PRA'"
run_test "seed-kit package metadata preview" "cd '$repo_dir' && tmp=\$(mktemp -d -t seed-kit-package-meta.XXXXXX) && mkdir -p \"\$tmp/source/compose\" \"\$tmp/source/config/caddy\" \"\$tmp/source/config/homepage\" \"\$tmp/output\" && printf '%s\n' 'services: {}' > \"\$tmp/source/compose/docker-compose.yml\" && printf '%s\n' ':80' > \"\$tmp/source/config/caddy/Caddyfile\" && printf '%s\n' 'title: rpi-edge' > \"\$tmp/source/config/homepage/settings.yaml\" && sh tools/service-package.sh create --service rpi-edge-vps --dry-run --output \"\$tmp/output\" --source \"\$tmp/source\" >/dev/null && out=\$(sh seed-kit.sh --plan --package \"\$tmp/output/rpi-edge-service.tar.gz\") && rm -rf \"\$tmp\" && printf '%s\n' \"\$out\" | grep -q 'Package ID: rpi-edge-service' && printf '%s\n' \"\$out\" | grep -q 'Profile: rpi-edge' && printf '%s\n' \"\$out\" | grep -q '  - docker' && printf '%s\n' \"\$out\" | grep -q 'Secrets policy: manual-reconnect'"
run_test "seed-kit package verify" "cd '$repo_dir' && tmp=\$(mktemp -d -t seed-kit-package-verify-smoke.XXXXXX) && mkdir -p \"\$tmp/source/compose\" \"\$tmp/source/config/caddy\" \"\$tmp/source/config/homepage\" \"\$tmp/output\" && printf '%s\n' 'services: {}' > \"\$tmp/source/compose/docker-compose.yml\" && printf '%s\n' ':80' > \"\$tmp/source/config/caddy/Caddyfile\" && printf '%s\n' 'title: rpi-edge' > \"\$tmp/source/config/homepage/settings.yaml\" && sh tools/service-package.sh create --service rpi-edge-vps --dry-run --output \"\$tmp/output\" --source \"\$tmp/source\" >/dev/null && out=\$(sh seed-kit.sh package verify \"\$tmp/output/rpi-edge-service.tar.gz\") && rm -rf \"\$tmp\" && printf '%s\n' \"\$out\" | grep -q 'Result: OK' && printf '%s\n' \"\$out\" | grep -q 'SHA256SUMS'"
run_test "seed-kit package stage" "cd '$repo_dir' && tmp=\$(mktemp -d -t seed-kit-package-stage-smoke.XXXXXX) && mkdir -p \"\$tmp/source/compose\" \"\$tmp/source/config/caddy\" \"\$tmp/source/config/homepage\" \"\$tmp/output\" && printf '%s\n' 'services: {}' > \"\$tmp/source/compose/docker-compose.yml\" && printf '%s\n' ':80' > \"\$tmp/source/config/caddy/Caddyfile\" && printf '%s\n' 'title: rpi-edge' > \"\$tmp/source/config/homepage/settings.yaml\" && sh tools/service-package.sh create --service rpi-edge-vps --dry-run --output \"\$tmp/output\" --source \"\$tmp/source\" >/dev/null && out=\$(sh seed-kit.sh package stage \"\$tmp/output/rpi-edge-service.tar.gz\") && stage_dir=\$(printf '%s\n' \"\$out\" | sed -n 's/^Stage dir: //p') && [ -n \"\$stage_dir\" ] && [ -d \"\$stage_dir\" ] && [ -f \"\$stage_dir/rpi-edge-service/seed-kit-package.sh\" ] && rm -rf \"\$stage_dir\" \"\$tmp\" && printf '%s\n' \"\$out\" | grep -q 'Package staged' && printf '%s\n' \"\$out\" | grep -q 'No system changes were made.'"
run_test "seed-kit package inspect-stage" "cd '$repo_dir' && tmp=\$(mktemp -d -t seed-kit-package-inspect-smoke.XXXXXX) && mkdir -p \"\$tmp/source/compose\" \"\$tmp/source/config/caddy\" \"\$tmp/source/config/homepage\" \"\$tmp/output\" && printf '%s\n' 'services: {}' > \"\$tmp/source/compose/docker-compose.yml\" && printf '%s\n' ':80' > \"\$tmp/source/config/caddy/Caddyfile\" && printf '%s\n' 'title: rpi-edge' > \"\$tmp/source/config/homepage/settings.yaml\" && sh tools/service-package.sh create --service rpi-edge-vps --dry-run --output \"\$tmp/output\" --source \"\$tmp/source\" >/dev/null && stage_out=\$(sh seed-kit.sh package stage \"\$tmp/output/rpi-edge-service.tar.gz\") && stage_dir=\$(printf '%s\n' \"\$stage_out\" | sed -n 's/^Stage dir: //p') && mock_stage=/tmp/seed-kit-package-stage.mock && rm -rf \"\$mock_stage\" && cp -R \"\$stage_dir\" \"\$mock_stage\" && out=\$(sh seed-kit.sh package inspect-stage \"\$mock_stage\") && sh seed-kit.sh package inspect-stage /tmp >/tmp/seed-kit-inspect-invalid.out 2>&1; invalid_rc=\$?; rm -rf \"\$stage_dir\" \"\$mock_stage\" \"\$tmp\" /tmp/seed-kit-inspect-invalid.out && [ \"\$invalid_rc\" -ne 0 ] && printf '%s\n' \"\$out\" | grep -q 'Package ID: rpi-edge-service' && printf '%s\n' \"\$out\" | grep -q 'Node role: edge-service' && printf '%s\n' \"\$out\" | grep -q 'services detected:' && printf '%s\n' \"\$out\" | grep -q 'No restore, compose up, secrets, DNS/cutover'"
run_test "seed-kit package apply-guided" "cd '$repo_dir' && tmp=\$(mktemp -d -t seed-kit-package-guided-smoke.XXXXXX) && mkdir -p \"\$tmp/source/compose\" \"\$tmp/source/config/caddy\" \"\$tmp/source/config/homepage\" \"\$tmp/output\" && printf '%s\n' 'services: {}' > \"\$tmp/source/compose/docker-compose.yml\" && printf '%s\n' ':80' > \"\$tmp/source/config/caddy/Caddyfile\" && printf '%s\n' 'title: rpi-edge' > \"\$tmp/source/config/homepage/settings.yaml\" && sh tools/service-package.sh create --service rpi-edge-vps --dry-run --output \"\$tmp/output\" --source \"\$tmp/source\" >/dev/null && out=\$(sh seed-kit.sh package apply-guided \"\$tmp/output/rpi-edge-service.tar.gz\") && stage_dir=\$(printf '%s\n' \"\$out\" | sed -n 's/^Stage dir: //p' | tail -n 1) && rm -rf \"\$stage_dir\" \"\$tmp\" && printf '%s\n' \"\$out\" | grep -q 'PACKAGE APPLY GUIDED' && printf '%s\n' \"\$out\" | grep -q '\\[5/5\\] SAFE status' && printf '%s\n' \"\$out\" | grep -q 'No service was started.' && printf '%s\n' \"\$out\" | grep -q 'Package apply remains disabled in V1.'"
run_test "seed-kit package apply-guided install-modules confirm" "cd '$repo_dir' && tmp=\$(mktemp -d -t seed-kit-package-guided-step-smoke.XXXXXX) && mkdir -p \"\$tmp/source/compose\" \"\$tmp/source/config/caddy\" \"\$tmp/source/config/homepage\" \"\$tmp/output\" && printf '%s\n' 'services: {}' > \"\$tmp/source/compose/docker-compose.yml\" && printf '%s\n' ':80' > \"\$tmp/source/config/caddy/Caddyfile\" && printf '%s\n' 'title: rpi-edge' > \"\$tmp/source/config/homepage/settings.yaml\" && sh tools/service-package.sh create --service rpi-edge-vps --dry-run --output \"\$tmp/output\" --source \"\$tmp/source\" >/dev/null && out=\$(printf 'n\n' | sh seed-kit.sh package apply-guided \"\$tmp/output/rpi-edge-service.tar.gz\" --step install-modules 2>&1); rc=\$?; stage_dir=\$(printf '%s\n' \"\$out\" | sed -n 's/^Stage dir: //p' | tail -n 1); rm -rf \"\$stage_dir\" \"\$tmp\" && printf '%s\n' \"\$out\" | grep -q 'install-modules step' && { { [ \"\$rc\" -ne 0 ] && printf '%s\n' \"\$out\" | grep -q 'SAFE APPLY CONFIRMATION' && printf '%s\n' \"\$out\" | grep -q 'aborted by user'; } || printf '%s\n' \"\$out\" | grep -q 'No install-only modules selected'; }"
run_test "seed-kit package apply-guided review-configs" "cd '$repo_dir' && tmp=\$(mktemp -d -t seed-kit-package-review-smoke.XXXXXX) && mkdir -p \"\$tmp/source/compose\" \"\$tmp/source/config/caddy\" \"\$tmp/source/config/homepage\" \"\$tmp/output\" && printf '%s\n' 'services: {}' > \"\$tmp/source/compose/docker-compose.yml\" && printf '%s\n' ':80' > \"\$tmp/source/config/caddy/Caddyfile\" && printf '%s\n' 'title: rpi-edge' > \"\$tmp/source/config/homepage/settings.yaml\" && sh tools/service-package.sh create --service rpi-edge-vps --dry-run --output \"\$tmp/output\" --source \"\$tmp/source\" >/dev/null && out=\$(sh seed-kit.sh package apply-guided \"\$tmp/output/rpi-edge-service.tar.gz\" --step review-configs) && stage_dir=\$(printf '%s\n' \"\$out\" | sed -n 's/^Stage dir: //p' | tail -n 1) && rm -rf \"\$stage_dir\" \"\$tmp\" && printf '%s\n' \"\$out\" | grep -q 'CONFIG REVIEW' && printf '%s\n' \"\$out\" | grep -q 'services/docker-compose.yml' && printf '%s\n' \"\$out\" | grep -q 'configs/caddy/Caddyfile' && printf '%s\n' \"\$out\" | grep -q 'No files were copied.'"
run_test "seed-kit package apply-guided validate-services" "cd '$repo_dir' && tmp=\$(mktemp -d -t seed-kit-package-validate-smoke.XXXXXX) && mkdir -p \"\$tmp/source/compose\" \"\$tmp/source/config/caddy\" \"\$tmp/source/config/homepage\" \"\$tmp/output\" && printf '%s\n' 'services: {}' > \"\$tmp/source/compose/docker-compose.yml\" && printf '%s\n' ':80' > \"\$tmp/source/config/caddy/Caddyfile\" && printf '%s\n' 'title: rpi-edge' > \"\$tmp/source/config/homepage/settings.yaml\" && sh tools/service-package.sh create --service rpi-edge-vps --dry-run --output \"\$tmp/output\" --source \"\$tmp/source\" >/dev/null && out=\$(sh seed-kit.sh package apply-guided \"\$tmp/output/rpi-edge-service.tar.gz\" --step validate-services) && stage_dir=\$(printf '%s\n' \"\$out\" | sed -n 's/^Stage dir: //p' | tail -n 1) && rm -rf \"\$stage_dir\" \"\$tmp\" && printf '%s\n' \"\$out\" | grep -q 'SERVICE VALIDATION' && printf '%s\n' \"\$out\" | grep -q 'docker compose:' && printf '%s\n' \"\$out\" | grep -q 'homepage configs:' && printf '%s\n' \"\$out\" | grep -q 'No services were started.' && printf '%s\n' \"\$out\" | grep -q 'No configs were copied.'"
run_test "seed-kit package apply-guided deploy-configs" "cd '$repo_dir' && tmp=\$(mktemp -d -t seed-kit-package-deploy-smoke.XXXXXX) && mkdir -p \"\$tmp/source/compose\" \"\$tmp/source/config/caddy\" \"\$tmp/source/config/homepage\" \"\$tmp/output\" \"\$tmp/home\" && printf '%s\n' 'services: {}' > \"\$tmp/source/compose/docker-compose.yml\" && printf '%s\n' ':80' > \"\$tmp/source/config/caddy/Caddyfile\" && printf '%s\n' 'title: rpi-edge' > \"\$tmp/source/config/homepage/settings.yaml\" && sh tools/service-package.sh create --service rpi-edge-vps --dry-run --output \"\$tmp/output\" --source \"\$tmp/source\" >/dev/null && out=\$(printf 'y\ny\ny\ny\n' | HOME=\"\$tmp/home\" sh seed-kit.sh package apply-guided \"\$tmp/output/rpi-edge-service.tar.gz\" --step deploy-configs) && stage_dir=\$(printf '%s\n' \"\$out\" | sed -n 's/^Stage dir: //p' | tail -n 1) && [ -f \"\$tmp/home/seed-kit-deploy/rpi-edge/docker-compose.yml\" ] && [ -f \"\$tmp/home/seed-kit-deploy/rpi-edge/Caddyfile\" ] && [ -f \"\$tmp/home/seed-kit-deploy/rpi-edge/homepage/settings.yaml\" ] && rm -rf \"\$stage_dir\" \"\$tmp\" && printf '%s\n' \"\$out\" | grep -q 'GUIDED CONFIG DEPLOYMENT' && printf '%s\n' \"\$out\" | grep -q 'Copied:' && printf '%s\n' \"\$out\" | grep -q 'No compose up/pull' && printf '%s\n' \"\$out\" | grep -q 'Staging kept for inspection.'"
run_test "seed-kit package apply-guided validate-deployed" "cd '$repo_dir' && tmp=\$(mktemp -d -t seed-kit-package-deployed-smoke.XXXXXX) && mkdir -p \"\$tmp/source/compose\" \"\$tmp/source/config/caddy\" \"\$tmp/source/config/homepage\" \"\$tmp/output\" \"\$tmp/home/seed-kit-deploy/rpi-edge/homepage\" && printf '%s\n' 'services: {}' > \"\$tmp/source/compose/docker-compose.yml\" && printf '%s\n' ':80' > \"\$tmp/source/config/caddy/Caddyfile\" && printf '%s\n' 'title: rpi-edge' > \"\$tmp/source/config/homepage/settings.yaml\" && cp \"\$tmp/source/compose/docker-compose.yml\" \"\$tmp/home/seed-kit-deploy/rpi-edge/docker-compose.yml\" && cp \"\$tmp/source/config/caddy/Caddyfile\" \"\$tmp/home/seed-kit-deploy/rpi-edge/Caddyfile\" && cp \"\$tmp/source/config/homepage/settings.yaml\" \"\$tmp/home/seed-kit-deploy/rpi-edge/homepage/settings.yaml\" && sh tools/service-package.sh create --service rpi-edge-vps --dry-run --output \"\$tmp/output\" --source \"\$tmp/source\" >/dev/null && out=\$(HOME=\"\$tmp/home\" sh seed-kit.sh package apply-guided \"\$tmp/output/rpi-edge-service.tar.gz\" --step validate-deployed) && stage_dir=\$(printf '%s\n' \"\$out\" | sed -n 's/^Stage dir: //p' | tail -n 1) && rm -rf \"\$stage_dir\" \"\$tmp\" && printf '%s\n' \"\$out\" | grep -q 'DEPLOYED CONFIG VALIDATION' && printf '%s\n' \"\$out\" | grep -q '~/seed-kit-deploy/rpi-edge/' && printf '%s\n' \"\$out\" | grep -q 'homepage configs:' && printf '%s\n' \"\$out\" | grep -q 'Suggested next manual steps:' && printf '%s\n' \"\$out\" | grep -q 'No services were started.' && printf '%s\n' \"\$out\" | grep -q 'No configs were copied.'"
run_test "seed-kit package apply-guided suggest-start" "cd '$repo_dir' && tmp=\$(mktemp -d -t seed-kit-package-start-smoke.XXXXXX) && mkdir -p \"\$tmp/source/compose\" \"\$tmp/source/config/caddy\" \"\$tmp/source/config/homepage\" \"\$tmp/output\" \"\$tmp/home/seed-kit-deploy/rpi-edge/homepage\" && printf '%s\n' 'services: {}' > \"\$tmp/source/compose/docker-compose.yml\" && printf '%s\n' ':80' > \"\$tmp/source/config/caddy/Caddyfile\" && printf '%s\n' 'title: rpi-edge' > \"\$tmp/source/config/homepage/settings.yaml\" && cp \"\$tmp/source/compose/docker-compose.yml\" \"\$tmp/home/seed-kit-deploy/rpi-edge/docker-compose.yml\" && cp \"\$tmp/source/config/caddy/Caddyfile\" \"\$tmp/home/seed-kit-deploy/rpi-edge/Caddyfile\" && cp \"\$tmp/source/config/homepage/settings.yaml\" \"\$tmp/home/seed-kit-deploy/rpi-edge/homepage/settings.yaml\" && sh tools/service-package.sh create --service rpi-edge-vps --dry-run --output \"\$tmp/output\" --source \"\$tmp/source\" >/dev/null && out=\$(HOME=\"\$tmp/home\" sh seed-kit.sh package apply-guided \"\$tmp/output/rpi-edge-service.tar.gz\" --step suggest-start) && stage_dir=\$(printf '%s\n' \"\$out\" | sed -n 's/^Stage dir: //p' | tail -n 1) && rm -rf \"\$stage_dir\" \"\$tmp\" && printf '%s\n' \"\$out\" | grep -q 'SUGGESTED MANUAL START' && printf '%s\n' \"\$out\" | grep -q 'docker compose up -d' && printf '%s\n' \"\$out\" | grep -q 'sudo tailscale up' && printf '%s\n' \"\$out\" | grep -q 'cloudflared tunnel login/create/configure' && printf '%s\n' \"\$out\" | grep -q 'Seed-Kit did not start services.'"
run_fail_test "seed-kit package apply preview refused" "cd '$repo_dir' && pkg=\$(mktemp -t seed-kit-package-apply.XXXXXX) && sh seed-kit.sh --apply --package \"\$pkg\" --components docker >/tmp/seed-kit-package-apply.out 2>&1; rc=\$?; rm -f \"\$pkg\" /tmp/seed-kit-package-apply.out; exit \$rc"
run_test "seed-kit doctor" "cd '$repo_dir' && out=\$(sh seed-kit.sh doctor) && printf '%s\n' \"\$out\" | grep -q 'Seed-Kit doctor' && printf '%s\n' \"\$out\" | grep -q 'mode: read-only' && printf '%s\n' \"\$out\" | grep -q 'No changes were made.'"
run_test "seed-kit inspect" "cd '$repo_dir' && out=\$(sh seed-kit.sh inspect) && printf '%s\n' \"\$out\" | grep -q 'Seed-Kit inspect' && printf '%s\n' \"\$out\" | grep -q 'mode: read-only' && printf '%s\n' \"\$out\" | grep -q 'No changes were made.'"
run_test "profile-state syntax" "cd '$repo_dir' && sh -n tools/profile-state.sh"
run_test "service-package syntax" "cd '$repo_dir' && sh -n tools/service-package.sh"
run_test "profile-state smoke syntax" "cd '$repo_dir' && sh -n tests/profile-state-smoke.sh"
run_test "service-package smoke syntax" "cd '$repo_dir' && sh -n tests/service-package-smoke.sh"
run_test "profile-state" "cd '$repo_dir' && sh tests/profile-state-smoke.sh"
run_test "service-package" "cd '$repo_dir' && sh tests/service-package-smoke.sh"

echo "summary:"
echo "  total: $total"
echo "  failed: $failures"

if [ "$failures" -eq 0 ]; then
  echo "smoke tests OK"
  exit 0
fi

echo "smoke tests FAILED" >&2
exit 1
